name: junit-xml
version: 0.1.0.2
synopsis: Producing JUnit-style XML test reports.
description: Please see the README at <https://github.com/jwoudenberg/junit-xml>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2020 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/junit-xml#readme
license-file: LICENSE
category: Web
github: jwoudenberg/junit-xml
extra-doc-files:
- README.md
- CHANGELOG.md
data-files:
- test/sample-report.xml
library:
  dependencies:
  - base >= 4.10.1.0 && < 5
  - text
  - xml-conduit >= 1.5.0 && < 1.10
  exposed-modules:
  - Text.XML.JUnit
  source-dirs: src
tests:
  spec:
    dependencies:
    - base
    - junit-xml
    - tasty-golden >= 2.3 && < 2.4
    - tasty >= 1.1 && < 1.5
    main: Main.hs
    source-dirs:
    - test
